// <auto-generated />
namespace kursov.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _12333 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_12333));
        
        string IMigrationMetadata.Id
        {
            get { return "201801181520407_12333"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
